name: sphinx_docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the project
    - uses: actions/checkout@v2.4.0
      with:
        path: "repo"

    # Build HTML docs
    - uses: ammaraskar/sphinx-action@0.4
      with:
        # Make sure we install Doxygen, we use it for scanning vpinball.idl
        pre-build-command: "apt install -y doxygen"
        docs-folder: "repo/doc/"

    # Publish built docs to gh-pages branch
    - name: Commit documentation changes to gh-pages
      run: |
        # The first command tries to clone vpinball on the `gh-pages` branch. If it fails, we clone from the default
        # branch, create a `gh-pages` branch, and unstage/delete everything in it
        git clone https://github.com/${GITHUB_REPOSITORY}.git pages --branch gh-pages || (git clone https://github.com/${GITHUB_REPOSITORY}.git pages --depth=1 && git -C pages symbolic-ref HEAD refs/heads/gh-pages && rm pages/.git/index && git -C pages clean -fdx)
        rm -r pages/* || true # Remove all non-hidden files (so .git isn't removed)
        cp -r repo/doc/build/html/* pages
        cd pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        # This command will fail if no changes were present, so we ignore that.
        git commit -m "Update documentation" -a || true

    - name: Push changes to gh-pages
      uses: ad-m/github-push-action@v0.6.0
      with:
        directory: pages
        branch: gh-pages
        github_token: ${{ github.token }}
